### ISSUE TITLE
斯卡布罗集市

### ISSUE THREAD

**Issue by livesun** [zytx121/je#390]
# 斯卡布罗集市

![image](https://user-images.githubusercontent.com/27534854/35423850-213d403a-028b-11e8-99d4-f8fc1390d6af.png)

## 歌曲信息

- 作曲：英格兰
- 歌手：莎拉·布莱曼

## 谱

```
226663432
6[1][2][1]6756
[2][2][2][1]665431
26543212

2226663432
6[1][2][1]67576
[2][2][2][1]665431
2654321432

2226663432
6[1][2][1]6756
[2][2][2][1]665431
2654321432
```

**Comment by zytx121** [comment]
#120
