### ISSUE TITLE
深海少女（简谱）

### ISSUE THREAD

**Issue by livesun** [zytx121/je#458]
# 深海少女

![shenhaishaotimg](https://user-images.githubusercontent.com/27534854/35760998-2f28f3ee-08bf-11e8-9743-40a57c2026de.jpg)

## 歌曲信息

- 作词：ゆうゆ
- 作曲：ゆうゆ
- 编曲：ゆうゆ
- 歌手：初音ミク

## 谱

![yaq2u 1 hrnh 379jhj 6 3](https://user-images.githubusercontent.com/27534854/35760962-e85f4850-08be-11e8-94a1-7e458768c8be.jpg)

![3yk a av 9g9h9 3ffu g](https://user-images.githubusercontent.com/27534854/35760963-ebe35f98-08be-11e8-8b1c-8fff72a5fe7b.jpg)

**Comment by zytx121** [comment]
123
